Implement Jenkins pipeline for CI/CD
Project-Lavinia/Lavinia-api pull request #44
Opened 2020-08-19 23:04 UTC by Log234

Implements a Jenkins pipeline which builds on new commits in GitHub and publishes to api.lavinia.no when the commits are on the master branch.

2020-08-24 15:54 UTC, simendag requested changes
I don't see tests being run here. Tests in addition need to not give a "failed build"-result in Jenkins but a yellow build. A failed build does not produce any artefacts. A failed test may/may not publish artefacts, but they should not be deployed.

2020-08-27 23:45 UTC, simendag commented on Jenkinsfile
> +          disableHostKeyChecking: true
What's this madness? This is not the kind of thing that stands up to a security review.

2020-08-27 23:46 UTC, simendag commented on Jenkinsfile
> +          disableHostKeyChecking: true
When you use SSH and don't check the host key, you have in principle no idea what computer you just connected to.

2020-08-27 23:47 UTC, simendag commented
It would be strongly preferred if we fixed the not-checking-hostkey thing before we merge it. Being that this is an open source project it's a pretty glaring security problem if someone does get into the network one way or another.

2021-09-21 15:39 UTC, simendag commented
This is ancient - should we just close it? I imagine you got this running in the end. :-P Everything I complained about was addressed anyway.

2021-09-25 22:43 UTC, Log234 commented
> 
> 
> This is ancient - should we just close it? I imagine you got this running in the end. :-P Everything I complained about was addressed anyway.

Agreed, let's close this PR.

2022-01-26 21:54 UTC, Log234 commented
Why did we actually close this? We clearly do not have any Jenkins file in the development or master branch...?

2022-01-28 19:23 UTC, simendag approved these changes
Seems fine - will need an update for upgrade to .NET 6 on later occasion though, since we are not defining our own output for the release build 👍

2022-01-28 22:57 UTC, merged